spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/blog?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#tomcat端口
server:
  port: 80
audience:
  # 代表这个JWT的接收对象,存入audience
  clientId: 098f6bcd4621d373cade4e832627b4f6
  # 密钥, 经过Base64加密, 可自行替换
  base64Secret: AIk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY=
  # JWT的签发主体，存入issuer
  name: workhours
  # 过期时间，时间戳
  expiresSecond: -1
#日志记录级别
#logging:
#  level:
#    com.itheima: debug
#    org.springframework: info
#mybatis:
#  # 实体类别名包路径
#  type-aliases-package: com.itheima.pojo
#  # 映射文件路径
#  # mapper-locations: classpath:mappers/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl